# ===============================================================
# WARNING
# This file is not functional yet. Will be implemented later
# ===============================================================
repository:
  name: jraebrown/.dotfiles
  origin: git@github.com:jraebrown/.dotfiles.git
  raw: https://raw.githubusercontent.com/jraebrown/.dotfiles/main/

download:
  tarball: https://github.com/jraebrown/.dotfiles/tarball/main
  zip: https://github.com/jraebrown/.dotfiles/archive/main.zip
